# Generated by Django 6.0.1 on 2026-02-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
